#include "ESP32TrackerREV4.h"

//#define SELFTEST_PARAMETERS         SELFTEST_VOLTAGE | SELFTEST_LEDS | SELFTEST_WIFI_SCAN 
#define SELFTEST_PARAMETERS         SELFTEST_VOLTAGE | SELFTEST_LEDS | SELFTEST_HALLSENSOR | SELFTEST_I2C | SELFTEST_RTC | SELFTEST_ACCFOC_CHECK | SELFTEST_BARO | SELFTEST_FLASH_BAD_BLOCKS | SELFTEST_FLASH_READ_WRITE | SELFTEST_NVS_RESET | SELFTEST_CPU_CLOCK_DOWN | SELFTEST_WIFI_SCAN

ESP32TrackerREV4 device = ESP32TrackerREV4();

extern "C" void app_main() {
    while(1) {
        printf("HELLO WORLD!\n");
        device.selfTest(3750, SELFTEST_PARAMETERS);
        device.deepSleep();
    }
}