#define WIFI_SSID1        "xxxxxx"
#define WIFI_PASSWORD1    "xxxxxx"
#define WIFI_SSID2        "xxxxxx"
#define WIFI_PASSWORD2    "xxxxxx"
#define WIFI_SSID3        "xxxxxx"
#define WIFI_PASSWORD3    "xxxxxx"
